src/Entity/Contrat.php
<?php

namespace App\Entity;

use App\Repository\ContratRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ContratRepository::class)]
class Contrat
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $id_conducteur = null;

    #[ORM\Column]
    private ?int $id_admin = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_debut = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_fin = null;

    #[ORM\Column]
    private ?float $prix = null;

    #[ORM\Column(length: 255)]
    private ?string $statut = null;

    #[ORM\Column(length: 255)]
    private ?string $qrCode = null;

    #[ORM\ManyToOne(inversedBy: 'contrats')]
    private ?Abonnement $id_abonnement = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdConducteur(): ?int
    {
        return $this->id_conducteur;
    }

    public function setIdConducteur(int $id_conducteur): self
    {
        $this->id_conducteur = $id_conducteur;

        return $this;
    }

    public function getIdAdmin(): ?int
    {
        return $this->id_admin;
    }

    public function setIdAdmin(int $id_admin): self
    {
        $this->id_admin = $id_admin;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeInterface $date_debut): self
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(\DateTimeInterface $date_fin): self
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getStatut(): ?string
    {
        return $this->statut;
    }

    public function setStatut(string $statut): self
    {
        $this->statut = $statut;

        return $this;
    }

    public function getQrCode(): ?string
    {
        return $this->qrCode;
    }

    public function setQrCode(string $qrCode): self
    {
        $this->qrCode = $qrCode;

        return $this;
    }

    public function getIdAbonnement(): ?Abonnement
    {
        return $this->id_abonnement;
    }

    public function setIdAbonnement(?Abonnement $id_abonnement): self
    {
        $this->id_abonnement = $id_abonnement;

        return $this;
    }
}

src/Controller/ContratfController.php
<?php

namespace App\Controller;

use App\Entity\Contrat;
use App\Form\ContratType;
use App\Repository\ContratRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Dompdf\Options;

use Dompdf\Dompdf;

#[Route('/contratf')]
class ContratfController extends AbstractController
{
    #[Route('/', name: 'app_contratf_index', methods: ['GET'])]
    public function index(ContratRepository $contratRepository): Response
    {
        return $this->render('contratf/indexfront.html.twig', [
            'contrats' => $contratRepository->findAll(),
        ]);
    }

    #[Route('/back', name: 'app_contratb_index', methods: ['GET'])]
    public function indexB(ContratRepository $contratRepository): Response
    {
        return $this->render('contratf/indexback.html.twig', [
            'contrats' => $contratRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_contratf_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ContratRepository $contratRepository): Response
    {
        $contrat = new Contrat();
        $form = $this->createForm(ContratType::class, $contrat);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $contratRepository->save($contrat, true);

            return $this->redirectToRoute('app_contratf_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('contratf/new.html.twig', [
            'contrat' => $contrat,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_contratf_show', methods: ['GET'])]
    public function show(Contrat $contrat): Response
    {
        return $this->render('contratf/show.html.twig', [
            'contrat' => $contrat,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_contratf_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Contrat $contrat, ContratRepository $contratRepository): Response
    {
        $form = $this->createForm(ContratType::class, $contrat);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $contratRepository->save($contrat, true);

            return $this->redirectToRoute('app_contratf_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('contratf/edit.html.twig', [
            'contrat' => $contrat,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_contratf_delete', methods: ['POST'])]
    public function delete(Request $request, Contrat $contrat, ContratRepository $contratRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$contrat->getId(), $request->request->get('_token'))) {
            $contratRepository->remove($contrat, true);
        }

        return $this->redirectToRoute('app_contratf_index', [], Response::HTTP_SEE_OTHER);
    }
    // pdf method : 


    #[Route('/generate_pdf/{id}', name: 'generate_pdf', methods: ['GET', 'POST'])]
    public function generateContrat(Contrat $contrat)
    {

        $html = $this->renderView('contratf/pdf.html.twig', [
            'contrat' => $contrat
        ]);


        $options = new Options();
        $options->set('isRemoteEnabled', true);

        $dompdf = new Dompdf($options);
        $dompdf->loadHtml($html);
        $dompdf->setPaper('A4', 'portrait');
        $dompdf->render();

        $output = $dompdf->output();

        $response = new Response($output);
        $response->headers->set('Content-Type', 'application/pdf');
        $response->headers->set('Content-Disposition', 'inline; filename="contrat.pdf"');

        return $response;
    }

    //download pdf : 


    #[Route('/download_pdf/{id}', name: 'download_pdf', methods: ['GET', 'POST'])]

    public function downloadPdf(Contrat $contrat)
    {
        $options = new Options();
        $options->set('isRemoteEnabled', true);

        $dompdf = new Dompdf($options);

        // Render the HTML template for the PDF
        $html = $this->renderView('contratf/pdf.html.twig', [
            'contrat' => $contrat,
        ]);

        // Load the HTML into Dompdf
        $dompdf->loadHtml($html);

        // Set the paper size and orientation
        $dompdf->setPaper('A4', 'portrait');

        // Render the PDF
        $dompdf->render();

        // Get the PDF content as a string
        $pdfContent = $dompdf->output();

        // Create a new Symfony response with the PDF content
        $response = new Response($pdfContent);

        // Set the headers for a PDF file download
        $response->headers->set('Content-Type', 'application/pdf');
        $response->headers->set('Content-Disposition', 'attachment;filename="contrat_' . $contrat->getId() . '.pdf"');

        return $response;
    }

}

templates/contratf/_delete_form.html.twig
<form method="post" action="{{ path('app_contratf_delete', {'id': contrat.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ contrat.id) }}">
    <button class="btn">Delete</button>
</form>

templates/contratf/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/contratf/edit.html.twig
{% extends 'basefront.html.twig' %}
{% block title %}Edit Contrat{% endblock %}

{% block body %}
    <h1>Edit Contrat</h1>

    {{ include('contratf/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_contratf_index') }}">back to list</a>

    {{ include('contratf/_delete_form.html.twig') }}
{% endblock %}

templates/contratf/indexback.html.twig
{% extends 'baseback.html.twig' %}
{% block body %}
            <div class="container-fluid pt-4 px-4">
                <div class="bg-secondary text-center rounded p-4">
                    <div class="d-flex align-items-center justify-content-between mb-4">
                        <h6 class="mb-0">Contrat</h6>
                        <a href="{{ path('app_contratf_new') }}"> <button class="btn btn-primary" type="button">Ajouter</button></a>
                    </div>
                    <div class="table-responsive">
                        <table class="table text-start align-middle table-bordered table-hover mb-0">
                            <thead>
                              <tr>
                                <th>id</th>
                                <th>date debut</th>
                                <th>date fin</th>
                                <th>prix</th>
                                <th>actions</th>
                              </tr>
                            </thead>
                            <tbody>
                              {% for a in contrats %}
                                <tr>
                            <td>{{ a.id }}</td>
                             <td>
                              
                              {{a.dateDebut ? a.dateDebut|date('Y-m-d') : '' }}
                            </td>
                             <td>
                              
                              {{a.dateFin ? a.dateFin|date('Y-m-d') : '' }}
                            </td>
                            <td>{{ a.prix }}</td>
                              
                            <td style='display:flex'>                    
                            <a href="{{ path('app_contratf_edit',{'id': a.id}) }}"><button class="btn btn-primary" type="button">Modifier</button></a>
                            <a href="{{ path('app_contratf_delete',{'id': a.id}) }}">
                            <button class="btn btn-danger" type="button">Supprimer</button>
                            </a>
                            </td>

                           
                          </tr>
                              {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
{% endblock %} 

templates/contratf/indexfront.html.twig
{% extends 'basefront.html.twig' %}
{% block body %}
 <!-- Working Hours Start -->
    <div class="container-xxl py-5">
        <div class="container">





                                    <a href="{{ path('app_contratf_new') }}"> <button class="btn btn-primary" type="button">Ajouter</button></a>

                              {% for a in contrats %}
<a href="{{ path('generate_pdf',{'id': a.id}) }}" class="btn btn-primary">Generate PDF</a>
   <a href="{{ path('download_pdf',{'id': a.id}) }}" class="btn btn-primary">Download PDF</a>
                              {% endfor %}




            <div class="row g-0">
                <div class="col-lg-6 wow fadeIn" data-wow-delay="0.1s">
                    <div class="h-100">
                        <img class="img-fluid h-100" src="img/tunis.jpg" alt="">
                    </div>
                </div>
                <div class="col-lg-6 wow fadeIn" data-wow-delay="0.5s">
                    <div class="bg-secondary h-100 d-flex flex-column justify-content-center p-5">
                        <p class="d-inline-flex bg-dark text-primary py-1 px-4 me-auto">contrat </p>
                        <div>
                            {% for a in contrats %}
                            <div class="d-flex justify-content-between border-bottom py-2">
                                <h6 class="text-uppercase mb-0">id de contrat </h6>
                                <span class="text-uppercase">{{ a.id }}</span>
                            </div>
                             <div class="d-flex justify-content-between border-bottom py-2">
                                <h6 class="text-uppercase mb-0">id conducteur</h6>
                                <span class="text-uppercase">{{ a.idConducteur }}</span>
                            </div>
                            <div class="d-flex justify-content-between border-bottom py-2">
                                <h6 class="text-uppercase mb-0">date debut de contrat </h6>
                                <span class="text-uppercase">{{a.dateDebut ? a.dateDebut|date('Y-m-d') : '' }}</span>
                            </div>

                            <div class="d-flex justify-content-between border-bottom py-2">
                                <h6 class="text-uppercase mb-0">date fin de contrat </h6>
                                <span class="text-uppercase">{{a.dateFin ? a.dateFin|date('Y-m-d') : '' }}</span>
                            </div>
                            <div class="d-flex justify-content-between border-bottom py-2">
                                <h6 class="text-uppercase mb-0">prix</h6>
                                <span class="text-uppercase">{{ a.prix }}</span>
                            </div>
                             <div class="d-flex justify-content-between border-bottom py-2">
                                <h6 class="text-uppercase mb-0">statut</h6>
                                <span class="text-uppercase">{{ a.statut }}</span>
                            </div>
                            
                           

                            <div class="d-flex justify-content-between border-bottom py-2">


                            <a href="{{ path('app_contratf_edit',{'id': a.id}) }}">
                            <button class="btn btn-primary" type="button">Modifier</button></a>
                            <a href="{{ path('app_contratf_delete',{'id': a.id}) }}">
                             <button class="btn btn-primary" type="button">Supprimer</button></a>
                             </div>
                                                         {% endfor %}
 
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Working Hours End -->












            <div class="d-none">
                <div class="bg-secondary text-center rounded p-4">
                    <div class="d-flex align-items-center justify-content-between mb-4">
                        <h6 class="mb-0">Contrat</h6>
                        <a href="{{ path('app_contratf_new') }}"> <button class="btn btn-primary" type="button">Ajouter</button></a>
                    </div>
                    <div class="table-responsive">
                        <table class="table text-start align-middle table-bordered table-hover mb-0">
                            <thead>
                              <tr>
                              <th>   </th>
                                <th>id</th>
                                <th>date debut</th>
                                <th>date fin</th>
                                <th>prix</th>
                               
                              </tr>
                            </thead>
                            <tbody>
                              {% for a in contrats %}
                                <tr>
                            <td>{{ a.id }}</td>
                             <td>
                              
                              {{a.dateDebut ? a.dateDebut|date('Y-m-d') : '' }}
                            </td>
                             <td>
                              
                              {{a.dateFin ? a.dateFin|date('Y-m-d') : '' }}
                            </td>
                            <td>{{ a.prix }}</td>
                              
                            <td style='display:flex'>
  <a href="{{ path('generate_pdf',{'id': a.id}) }}" class="btn btn-primary">Generate PDF</a>
   <a href="{{ path('download_pdf',{'id': a.id}) }}" class="btn btn-primary">Download PDF</a>

                            <a href="{{ path('app_contratf_edit',{'id': a.id}) }}"><button class="btn btn-primary" type="button">Modifier</button></a>
                            <a href="{{ path('app_contratf_delete',{'id': a.id}) }}">
                            <button class="btn btn-danger" type="button">Supprimer</button>
                            </a>
                            </td>

                           
                          </tr>
                              {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
{% endblock %} 

templates/contratf/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Contrat{% endblock %}

{% block body %}
    <h1>Create new Contrat</h1>

    {{ include('contratf/_form.html.twig') }}

    <a href="{{ path('app_contratf_index') }}">back to list</a>
{% endblock %}

templates/contratf/pdf.html.twig
<!DOCTYPE html>
<html>
<head>
	<title style="color: red">Contrat {{ contrat.id }}</title>
	<style>
		body {

			font-family: Garamond, serif;
			color: black;
			line-height: 1.5;
			margin: 0;
			border: 5px solid black;
			padding: 20px;
			text-align: justify;
		}
		p {
			margin-top: 20px;
			margin-bottom: 20px;
			font-size: 18px;
		}
		strong {
			font-weight: bold;
		}
	</style>
</head>
<body>
<img src="http://localhost:8000/logn1.png" alt="AutoXpress Logo " style="width: 100px; position: absolute; top: 0; right: 0;">
	<p >Nous sommes ravis que vous cher conducteur d'id numero  {{ contrat.idConducteur }} </p>
	<p>soyez disposé à signer ce contrat  num : {{ contrat.id }}</p>
	<p>avec l admin d'ID : {{ contrat.idAdmin }}</p>
	<p>Nous sommes convaincus que vous serez satisfait de notre service et nous sommes impatients de vous fournir une expérience de Date Début: {{ contrat.dateDebut|date('d/m/Y') }}</p>
	<p><strong>jusqua Date Fin:</strong> {{ contrat.dateFin|date('d/m/Y') }}</p>
	<p><strong>avec le total Prix:</strong> {{ contrat.prix }}</p>
	<p><strong>le statut du contrat :</strong> {{ contrat.statut }}</p>
	<p><strong>QR Code:</strong> {{ contrat.qrCode }}</p>
	<p>Thank you for choosing our services.</p>
</body>
</html>

templates/contratf/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Contrat{% endblock %}

{% block body %}
    <h1>Contrat</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ contrat.id }}</td>
            </tr>
            <tr>
                <th>Id_conducteur</th>
                <td>{{ contrat.idConducteur }}</td>
            </tr>
            <tr>
                <th>Id_admin</th>
                <td>{{ contrat.idAdmin }}</td>
            </tr>
            <tr>
                <th>Date_debut</th>
                <td>{{ contrat.dateDebut ? contrat.dateDebut|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Date_fin</th>
                <td>{{ contrat.dateFin ? contrat.dateFin|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Prix</th>
                <td>{{ contrat.prix }}</td>
            </tr>
            <tr>
                <th>Statut</th>
                <td>{{ contrat.statut }}</td>
            </tr>
            <tr>
                <th>QrCode</th>
                <td>{{ contrat.qrCode }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_contratf_index') }}">back to list</a>

    <a href="{{ path('app_contratf_edit', {'id': contrat.id}) }}">edit</a>

    {{ include('contratf/_delete_form.html.twig') }}
{% endblock %}