src/Entity/Offre.php
<?php

namespace App\Entity;

use App\Repository\OffreRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: OffreRepository::class)]
class Offre
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $conducteur = null;

    #[ORM\Column(length: 255)]
    private ?string $destination = null;

    #[ORM\Column(length: 255)]
    private ?string $pt_depart = null;

    #[ORM\Column]
    private ?int $prix = null;

    #[ORM\Column(length: 255)]
    private ?string $typeVehicule = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getConducteur(): ?string
    {
        return $this->conducteur;
    }

    public function setConducteur(string $conducteur): self
    {
        $this->conducteur = $conducteur;

        return $this;
    }

    public function getDestination(): ?string
    {
        return $this->destination;
    }

    public function setDestination(string $destination): self
    {
        $this->destination = $destination;

        return $this;
    }

    public function getPtDepart(): ?string
    {
        return $this->pt_depart;
    }

    public function setPtDepart(string $pt_depart): self
    {
        $this->pt_depart = $pt_depart;

        return $this;
    }

    public function getPrix(): ?int
    {
        return $this->prix;
    }

    public function setPrix(int $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getTypeVehicule(): ?string
    {
        return $this->typeVehicule;
    }

    public function setTypeVehicule(string $typeVehicule): self
    {
        $this->typeVehicule = $typeVehicule;

        return $this;
    }
}

src/Form/OffreType.php
<?php

namespace App\Form;

use App\Entity\Offre;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class OffreType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('conducteur')
            ->add('destination')
            ->add('pt_depart')
            ->add('prix')
            ->add('typeVehicule')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Offre::class,
        ]);
    }
}

src/Controller/OffreController.php
<?php

namespace App\Controller;

use App\Entity\Offre;
use App\Form\OffreType;
use App\Repository\OffreRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/offre')]
class OffreController extends AbstractController
{
    #[Route('/', name: 'app_offre_index', methods: ['GET'])]
    public function index(OffreRepository $offreRepository): Response
    {
        return $this->render('offre/index.html.twig', [
            'offres' => $offreRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_offre_new', methods: ['GET', 'POST'])]
    public function new(Request $request, OffreRepository $offreRepository): Response
    {
        $offre = new Offre();
        $form = $this->createForm(OffreType::class, $offre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $offreRepository->save($offre, true);

            return $this->redirectToRoute('app_offre_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('offre/new.html.twig', [
            'offre' => $offre,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_offre_show', methods: ['GET'])]
    public function show(Offre $offre): Response
    {
        return $this->render('offre/show.html.twig', [
            'offre' => $offre,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_offre_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Offre $offre, OffreRepository $offreRepository): Response
    {
        $form = $this->createForm(OffreType::class, $offre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $offreRepository->save($offre, true);

            return $this->redirectToRoute('app_offre_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('offre/edit.html.twig', [
            'offre' => $offre,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_offre_delete', methods: ['POST'])]
    public function delete(Request $request, Offre $offre, OffreRepository $offreRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$offre->getId(), $request->request->get('_token'))) {
            $offreRepository->remove($offre, true);
        }

        return $this->redirectToRoute('app_offre_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/offre/_delete_form.html.twig
<form method="post" action="{{ path('app_offre_delete', {'id': offre.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ offre.id) }}">
    <button class="btn">Delete</button>
</form>

templates/offre/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/offre/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Offre{% endblock %}

{% block body %}
    <h1>Edit Offre</h1>

    {{ include('offre/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_offre_index') }}">back to list</a>

    {{ include('offre/_delete_form.html.twig') }}
{% endblock %}

templates/offre/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Offre index{% endblock %}

{% block body %}
    <h1>Offre index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Conducteur</th>
                <th>Destination</th>
                <th>Pt_depart</th>
                <th>Prix</th>
                <th>TypeVehicule</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for offre in offres %}
            <tr>
                <td>{{ offre.id }}</td>
                <td>{{ offre.conducteur }}</td>
                <td>{{ offre.destination }}</td>
                <td>{{ offre.ptDepart }}</td>
                <td>{{ offre.prix }}</td>
                <td>{{ offre.typeVehicule }}</td>
                <td>
                    <a href="{{ path('app_offre_show', {'id': offre.id}) }}">show</a>
                    <a href="{{ path('app_offre_edit', {'id': offre.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_offre_new') }}">Create new</a>
{% endblock %}

templates/offre/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Offre{% endblock %}

{% block body %}
    <h1>Create new Offre</h1>

    {{ include('offre/_form.html.twig') }}

    <a href="{{ path('app_offre_index') }}">back to list</a>
{% endblock %}

templates/offre/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Offre{% endblock %}

{% block body %}
    <h1>Offre</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ offre.id }}</td>
            </tr>
            <tr>
                <th>Conducteur</th>
                <td>{{ offre.conducteur }}</td>
            </tr>
            <tr>
                <th>Destination</th>
                <td>{{ offre.destination }}</td>
            </tr>
            <tr>
                <th>Pt_depart</th>
                <td>{{ offre.ptDepart }}</td>
            </tr>
            <tr>
                <th>Prix</th>
                <td>{{ offre.prix }}</td>
            </tr>
            <tr>
                <th>TypeVehicule</th>
                <td>{{ offre.typeVehicule }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_offre_index') }}">back to list</a>

    <a href="{{ path('app_offre_edit', {'id': offre.id}) }}">edit</a>

    {{ include('offre/_delete_form.html.twig') }}
{% endblock %}